# Copyright 2019 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Add the haproxy repo
  apt_repository:
    repo: ppa:vbernat/haproxy-2.0
    update_cache: True
    state: present

- name: Install haproxy
  apt:
    name: haproxy
    state: present

- name: Remove softlink of haproxy from /etc/systemd/system/multi-user.target.wants
  file:
    state: absent
    path: "/etc/systemd/system/multi-user.target.wants/haproxy.service"

- name: Download dataplaneapi
  get_url:
    url: '{{ dataplane_url }}'
    dest: /usr/local/bin/dataplaneapi
    mode: 0755

- name: Copy haproxy.service to /etc/systemd/system
  copy:
    src: /lib/systemd/system/haproxy.service
    dest: /etc/systemd/system/haproxy.service
    remote_src: yes
    owner: root
    group: root
    mode: 0644

- name: set After with cloud-final.service
  replace:
    path: /etc/systemd/system/haproxy.service
    regexp: 'After=network.target rsyslog.service'
    replace: 'After=network.target rsyslog.service cloud-final.service'

- name: set WantedBy with cloud-init.target
  replace:
    path: /etc/systemd/system/haproxy.service
    regexp: 'WantedBy=multi-user.target'
    replace: 'WantedBy=cloud-init.target'

- name: enable haproxy service and ensure it is not masked
  systemd:
    name: haproxy
    enabled: yes
    masked: no
