# Copyright 2018 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- include_tasks: aws.yml
  when: packer_builder_type.startswith('amazon') 

- include_tasks: azure.yml
  when: packer_builder_type.startswith('azure') 

- include_tasks: vmware.yml
  when: packer_builder_type is search('vsphere-clone')

- include_tasks: googlecompute.yml
  when: packer_builder_type.startswith('googlecompute')

- name: set cloudinit feature flags
  copy:
    src: usr/lib/python3/dist-packages/cloudinit/feature_overrides.py
    dest: /usr/lib/python3/dist-packages/cloudinit/feature_overrides.py
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"
